# Generated by Django 3.1.6 on 2021-07-04 19:23

import car_dealer.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_name', to='car_dealer.make')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Semi-Automatic', 'Semi-Automatic')], max_length=300)),
                ('mileage', models.PositiveIntegerField()),
                ('engine', models.PositiveIntegerField(help_text="Please enter engine size as cc value - Example '1998' - Do not add cc at end of number.")),
                ('fuel_type', models.CharField(choices=[('BioFuel', 'BioFuel'), ('Hybrid-Petrol/Electric', 'Hybrid-Petrol/Electric'), ('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid-Petrol/Electric Plug-in', 'Hybrid-Petrol/Electric Plug-in')], max_length=50)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('body_style', models.CharField(choices=[('Hatch', 'Hatchback'), ('Estate', 'Estate'), ('SUV', 'SUV'), ('Saloon', 'Saloon'), ('Coupe', 'Coupe'), ('Convert', 'Convertible'), ('MPV', 'MPV'), ('Pick', 'Pickup')], max_length=20)),
                ('colour', models.CharField(max_length=20)),
                ('doors', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField()),
                ('insurance_group', models.PositiveIntegerField(help_text='Please enter insurance group in range of 1-50 - Enter numbers only.')),
                ('zero_sixty', models.DecimalField(decimal_places=1, default=0, help_text="Enter numbers only - Example '4.6'", max_digits=2)),
                ('top_speed', models.DecimalField(decimal_places=2, default=0, help_text="Enter number value only - Example '155'.", max_digits=5)),
                ('desctiption', models.TextField()),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='car_dealer.make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='car_dealer.model')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=car_dealer.models.rename)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car_dealer.vehicle')),
            ],
        ),
    ]
