# Generated by Django 3.1.6 on 2021-07-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0003_auto_20210706_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='desctiption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='top_speed',
            field=models.DecimalField(decimal_places=1, default=0, help_text="Enter number value only - Example '155'.", max_digits=5),
        ),
    ]
